export const activityList = [
    {
        activity_id: 1,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1676679806000",
        amount: -6.33,
    },
    {
        activity_id: 2,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1656451035000",
        amount: -3.97,
    },
    {
        activity_id: 3,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1663667631000",
        amount: 9.65,
    },
    {
        activity_id: 4,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1676113575000",
        amount: -6.0,
    },
    {
        activity_id: 5,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1664785957000",
        amount: -4.32,
    },
    {
        activity_id: 6,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1661293119000",
        amount: 3.44,
    },
    {
        activity_id: 7,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1659176714000",
        amount: -2.68,
    },
    {
        activity_id: 8,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1654261618000",
        amount: 7.36,
    },
    {
        activity_id: 9,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1667845642000",
        amount: 4.23,
    },
    {
        activity_id: 10,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1664676320000",
        amount: -5.42,
    },
    {
        activity_id: 11,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1677244586000",
        amount: 5.89,
    },
    {
        activity_id: 12,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1668995276000",
        amount: 2.14,
    },
    {
        activity_id: 13,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1666849808000",
        amount: 7.85,
    },
    {
        activity_id: 14,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1676487375000",
        amount: 6.71,
    },
    {
        activity_id: 15,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1658139648000",
        amount: 6.14,
    },
    {
        activity_id: 16,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1673601161000",
        amount: 1.81,
    },
    {
        activity_id: 17,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1655904260000",
        amount: 1.28,
    },
    {
        activity_id: 18,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1671277917000",
        amount: 5.97,
    },
    {
        activity_id: 19,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1665223252000",
        amount: 8.42,
    },
    {
        activity_id: 20,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1679665188000",
        amount: -6.37,
    },
    {
        activity_id: 21,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1668362657000",
        amount: 5.17,
    },
    {
        activity_id: 22,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1671827265000",
        amount: 1.99,
    },
    {
        activity_id: 23,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1656699847000",
        amount: 6.11,
    },
    {
        activity_id: 24,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1656983867000",
        amount: -6.17,
    },
    {
        activity_id: 25,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1654014513000",
        amount: 6.5,
    },
    {
        activity_id: 26,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1681166229000",
        amount: 8.44,
    },
    {
        activity_id: 27,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1679758966000",
        amount: -3.15,
    },
    {
        activity_id: 28,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1682485534000",
        amount: -8.46,
    },
    {
        activity_id: 29,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1657344559000",
        amount: 8.28,
    },
    {
        activity_id: 30,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1663711440000",
        amount: 4.14,
    },
    {
        activity_id: 31,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1683863607000",
        amount: 9.83,
    },
    {
        activity_id: 32,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1654097928000",
        amount: -3.06,
    },
    {
        activity_id: 33,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1664755983000",
        amount: 2.61,
    },
    {
        activity_id: 34,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1660568514000",
        amount: 1.12,
    },
    {
        activity_id: 35,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1682726364000",
        amount: 8.48,
    },
    {
        activity_id: 36,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1652771307000",
        amount: -7.54,
    },
    {
        activity_id: 37,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1672111175000",
        amount: 7.16,
    },
    {
        activity_id: 38,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1671039682000",
        amount: -2.79,
    },
    {
        activity_id: 39,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1665146659000",
        amount: 6.26,
    },
    {
        activity_id: 40,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1654792501000",
        amount: 4.24,
    },
    {
        activity_id: 41,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1668070456000",
        amount: -2.26,
    },
    {
        activity_id: 42,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1683328410000",
        amount: 3.88,
    },
    {
        activity_id: 43,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1681122469000",
        amount: -8.27,
    },
    {
        activity_id: 44,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1668858031000",
        amount: 9.52,
    },
    {
        activity_id: 45,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1663157497000",
        amount: -3.79,
    },
    {
        activity_id: 46,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1665027339000",
        amount: 5.39,
    },
    {
        activity_id: 47,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1665202770000",
        amount: 0.93,
    },
    {
        activity_id: 48,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1675279897000",
        amount: -5.54,
    },
    {
        activity_id: 49,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1654390425000",
        amount: 0.84,
    },
    {
        activity_id: 50,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1669487304000",
        amount: -6.49,
    },
    {
        activity_id: 51,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1670067389000",
        amount: -1.51,
    },
    {
        activity_id: 52,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1664037760000",
        amount: 9.73,
    },
    {
        activity_id: 53,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1664725185000",
        amount: 9.55,
    },
    {
        activity_id: 54,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1667237192000",
        amount: 4.98,
    },
    {
        activity_id: 55,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1681778366000",
        amount: -5.04,
    },
    {
        activity_id: 56,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1659283813000",
        amount: -4.23,
    },
    {
        activity_id: 57,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1662098842000",
        amount: 9.49,
    },
    {
        activity_id: 58,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1661486298000",
        amount: 4.33,
    },
    {
        activity_id: 59,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1681572610000",
        amount: -2.58,
    },
    {
        activity_id: 60,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1664458651000",
        amount: -0.5,
    },
    {
        activity_id: 61,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1672657283000",
        amount: -8.97,
    },
    {
        activity_id: 62,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1666992211000",
        amount: 3.93,
    },
    {
        activity_id: 63,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1673509337000",
        amount: 2.23,
    },
    {
        activity_id: 64,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1660244320000",
        amount: -3.79,
    },
    {
        activity_id: 65,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Insurance",
        account_name: "LTC",
        transaction_date: "1674850986000",
        amount: -2.92,
    },
    {
        activity_id: 66,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1657646591000",
        amount: 2.53,
    },
    {
        activity_id: 67,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1673294459000",
        amount: 5.95,
    },
    {
        activity_id: 68,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1671817391000",
        amount: 0.9,
    },
    {
        activity_id: 69,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1666349863000",
        amount: -7.79,
    },
    {
        activity_id: 70,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1660634498000",
        amount: -3.88,
    },
    {
        activity_id: 71,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Alfredo Elliott",
        account_name: "BTC",
        transaction_date: "1682118498000",
        amount: 8.53,
    },
    {
        activity_id: 72,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1672691481000",
        amount: -5.97,
    },
    {
        activity_id: 73,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "BTC",
        transaction_date: "1670583681000",
        amount: -8.47,
    },
    {
        activity_id: 74,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1682881248000",
        amount: 4.3,
    },
    {
        activity_id: 75,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1680058039000",
        amount: 9.83,
    },
    {
        activity_id: 76,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1674869619000",
        amount: -2.31,
    },
    {
        activity_id: 77,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1658724827000",
        amount: 6.32,
    },
    {
        activity_id: 78,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1682673919000",
        amount: -2.17,
    },
    {
        activity_id: 79,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1668470427000",
        amount: 2.39,
    },
    {
        activity_id: 80,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1666117282000",
        amount: 4.41,
    },
    {
        activity_id: 81,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1675915381000",
        amount: 8.06,
    },
    {
        activity_id: 82,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1662386822000",
        amount: 1.56,
    },
    {
        activity_id: 83,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1675626040000",
        amount: 3.95,
    },
    {
        activity_id: 84,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1667214028000",
        amount: -7.7,
    },
    {
        activity_id: 85,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1667712048000",
        amount: 9.04,
    },
    {
        activity_id: 86,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1680589306000",
        amount: 5.4,
    },
    {
        activity_id: 87,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1663438671000",
        amount: -1.86,
    },
    {
        activity_id: 88,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1661697980000",
        amount: 5.1,
    },
    {
        activity_id: 89,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1670372414000",
        amount: 6.71,
    },
    {
        activity_id: 90,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1666381164000",
        amount: 5.12,
    },
    {
        activity_id: 91,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1657554369000",
        amount: -0.4,
    },
    {
        activity_id: 92,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "BTC",
        transaction_date: "1659868259000",
        amount: 3.21,
    },
    {
        activity_id: 93,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Electricity",
        account_name: "ETH",
        transaction_date: "1661993205000",
        amount: -5.77,
    },
    {
        activity_id: 94,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Insurance",
        account_name: "ETH",
        transaction_date: "1671331109000",
        amount: 3.87,
    },
    {
        activity_id: 95,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "BTC",
        transaction_date: "1666169818000",
        amount: -0.19,
    },
    {
        activity_id: 96,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Electricity",
        account_name: "LTC",
        transaction_date: "1652638017000",
        amount: -9.79,
    },
    {
        activity_id: 97,
        activity_type: { key: "property-coverage", title: "Property Coverage" },
        activity_name: "Alfredo Elliott",
        account_name: "LTC",
        transaction_date: "1661875551000",
        amount: -9.54,
    },
    {
        activity_id: 98,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Alfredo Elliott",
        account_name: "ETH",
        transaction_date: "1666552213000",
        amount: -0.49,
    },
    {
        activity_id: 99,
        activity_type: { key: "personal", title: "Personal" },
        activity_name: "Konnor Guzman",
        account_name: "ETH",
        transaction_date: "1660223508000",
        amount: -7.83,
    },
    {
        activity_id: 100,
        activity_type: { key: "utility-payment", title: "Utility Payment" },
        activity_name: "Konnor Guzman",
        account_name: "LTC",
        transaction_date: "1670674952000",
        amount: -8.22,
    },
];
