export const durationOptions = [
    {
        value: [0, 3600000],
        label: "Less 1 Hours",
    },
    {
        value: [3600000, 10800000],
        label: "1 to 3 Hours",
    },
    {
        value: [10800000, 21600000],
        label: "3 to 6 Hours",
    },
    {
        value: [21600000, 36000000],
        label: "6 to 10 Hours",
    },
    {
        value: [36000000],
        label: "More than 10 Hours",
    },
];

export const filtersOptions = [
    {
        value: 'level',
        label: 'Level'
    },
    {
        value: 'status',
        label: 'Status'
    },
    {
        value: 'lesson_count',
        label: 'Lesson Count'
    },
    {
        value: 'duration',
        label: 'Duration'
    },
    {
        value: 'rating',
        label: 'Rating'
    },
    {
        value: 'price',
        label: 'Price'
    },
    {
        value: 'earning',
        label: 'Earning'
    },
    {
        value: 'students',
        label: 'Students Count'
    }
]

export const courseStatusOptions = [
    {
        value: 'draft',
        label: 'Draft',
        color: 'info',
    },
    {
        value: 'published',
        label: 'Published',
        color: 'success',
    },
    {
        value: 'in-review',
        label: 'In Review',
        color: 'primary',
    },
    {
        value: 'disabled',
        label: 'Disabled',
        color: 'neutral',
    },
    {
        value: 'rejected',
        label: 'Rejected',
        color: 'error',
    },
]

export const levelOptions = [
    {
        value: 'l1',
        index: 1,
        label: 'Beginner'
    },
    {
        value: 'l2',
        index: 2,
        label: 'Intermediate'
    },
    {
        value: 'l3',
        index: 3,
        label: 'Upper Intermediate'
    },
    {
        value: 'l4',
        index: 4,
        label: 'Advanced'
    }
]

export const coursesList = [
    {
        course_id: 1,
        name: "Blockchain Technology and Smart Contracts",
        image: "/images/800x600.png",
        lesson_count: 40,
        duration: 5731143,
        category: "Data Analytics",
        students: 15207,
        level: 'l3',
        price: 16.88,
        rating: 4.3,
        earning: 728304,
        status: 'draft'
    },
    {
        course_id: 2,
        name: "Data Visualization and Dashboard Design",
        image: "/images/800x600.png",
        lesson_count: 25,
        duration: 23346431,
        category: "Data Analytics",
        students: 92665,
        level: 'l4',
        price: 36.79,
        rating: 4.74,
        earning: 893567,
        status: 'draft'
    },
    {
        course_id: 3,
        name: "Distributed Systems and Parallel Computing",
        image: "/images/800x600.png",
        lesson_count: 6,
        duration: 230026490,
        category: "E-commerce",
        students: 80705,
        level: 'l4',
        price: 12.26,
        rating: 4.92,
        earning: 166992,
        status: 'rejected'
    },
    {
        course_id: 4,
        name: "Cryptography and Network Security",
        image: "/images/800x600.png",
        lesson_count: 45,
        duration: 338519781,
        category: "Software Architecture",
        students: 53171,
        level: 'l3',
        price: 80.40,
        rating: 4.18,
        earning: 59472,
        status: 'draft'
    },
    {
        course_id: 5,
        name: "Data Visualization and Dashboard Design",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 190581708,
        category: "Data Analytics",
        students: 67795,
        level: 'l4',
        price: 99.98,
        rating: 4.95,
        earning: 286531,
        status: 'rejected'
    },
    {
        course_id: 6,
        name: "Human-Computer Interaction and User Experience Design",
        image: "/images/800x600.png",
        lesson_count: 31,
        duration: 185796021,
        category: "Computer Vision",
        students: 2617,
        level: 'l3',
        price: 47.86,
        rating: 4.35,
        earning: 676206,
        status: 'draft'
    },
    {
        course_id: 7,
        name: "Blockchain Technology and Smart Contracts",
        image: "/images/800x600.png",
        lesson_count: 32,
        duration: 180244445,
        category: "PHP",
        students: 10692,
        level: 'l4',
        price: 17.49,
        rating: 4.54,
        earning: 610243,
        status: 'rejected'
    },
    {
        course_id: 8,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 12,
        duration: 222743405,
        category: "Scrum",
        students: 2513,
        level: 'l1',
        price: 28.56,
        rating: 4.75,
        earning: 611922,
        status: 'draft'
    },
    {
        course_id: 9,
        name: "Artificial Neural Networks and Deep Learning",
        image: "/images/800x600.png",
        lesson_count: 21,
        duration: 297772482,
        category: "Artificial Intelligence",
        students: 41959,
        level: 'l1',
        price: 70.81,
        rating: 4.27,
        earning: 675342,
        status: 'published'
    },
    {
        course_id: 10,
        name: "Natural Language Processing and Text Mining",
        image: "/images/800x600.png",
        lesson_count: 41,
        duration: 164221437,
        category: "PHP",
        students: 29000,
        level: 'l2',
        price: 10.00,
        rating: 4.91,
        earning: 336214,
        status: 'draft'
    },
    {
        course_id: 11,
        name: "Virtual Reality and Augmented Reality",
        image: "/images/800x600.png",
        lesson_count: 41,
        duration: 287542441,
        category: "Web Design",
        students: 28706,
        level: 'l4',
        price: 16.71,
        rating: 4.46,
        earning: 227768,
        status: 'draft'
    },
    {
        course_id: 12,
        name: "Cryptography and Network Security",
        image: "/images/800x600.png",
        lesson_count: 24,
        duration: 57993822,
        category: "Data Science",
        students: 24208,
        level: 'l1',
        price: 46.35,
        rating: 4.24,
        earning: 910455,
        status: 'disabled'
    },
    {
        course_id: 13,
        name: "Cryptography and Network Security",
        image: "/images/800x600.png",
        lesson_count: 6,
        duration: 44585220,
        category: "JavaScript",
        students: 34231,
        level: 'l4',
        price: 53.25,
        rating: 4.79,
        earning: 535154,
        status: 'disabled'
    },
    {
        course_id: 14,
        name: "Computer Graphics and Animation",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 21624947,
        category: "Neural Networks",
        students: 58075,
        level: 'l4',
        price: 64.00,
        rating: 4.46,
        earning: 341983,
        status: 'rejected'
    },
    {
        course_id: 15,
        name: "Bioinformatics and Computational Biology",
        image: "/images/800x600.png",
        lesson_count: 19,
        duration: 300419664,
        category: "Agile Methodologies",
        students: 31909,
        level: 'l4',
        price: 54.09,
        rating: 4.57,
        earning: 438886,
        status: 'disabled'
    },
    {
        course_id: 16,
        name: "Distributed Systems and Parallel Computing",
        image: "/images/800x600.png",
        lesson_count: 47,
        duration: 260846203,
        category: "Deep Learning",
        students: 69255,
        level: 'l2',
        price: 82.29,
        rating: 4.05,
        earning: 498381,
        status: 'rejected'
    },
    {
        course_id: 17,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 20,
        duration: 59543418,
        category: "Natural Language Processing",
        students: 24023,
        level: 'l2',
        price: 49.96,
        rating: 4.02,
        earning: 876405,
        status: 'published'
    },
    {
        course_id: 18,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 42,
        duration: 8752580,
        category: "Ruby on Rails",
        students: 42832,
        level: 'l3',
        price: 32.10,
        rating: 4.05,
        earning: 300486,
        status: 'in-review'
    },
    {
        course_id: 19,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 325022706,
        category: "Software Testing",
        students: 86397,
        level: 'l1',
        price: 96.95,
        rating: 4.09,
        earning: 330553,
        status: 'published'
    },
    {
        course_id: 20,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 210855512,
        category: "Natural Language Processing",
        students: 38541,
        level: 'l4',
        price: 70.10,
        rating: 4.71,
        earning: 735352,
        status: 'published'
    },
    {
        course_id: 21,
        name: "Digital Signal Processing and Audio Engineering",
        image: "/images/800x600.png",
        lesson_count: 20,
        duration: 283200641,
        category: "Artificial Intelligence",
        students: 49797,
        level: 'l2',
        price: 16.65,
        rating: 4.76,
        earning: 335022,
        status: 'published'
    },
    {
        course_id: 22,
        name: "Operating Systems and System Programming",
        image: "/images/800x600.png",
        lesson_count: 41,
        duration: 43992758,
        category: "Data Science",
        students: 30123,
        level: 'l2',
        price: 40.21,
        rating: 4.53,
        earning: 361964,
        status: 'disabled'
    },
    {
        course_id: 23,
        name: "Bioinformatics and Computational Biology",
        image: "/images/800x600.png",
        lesson_count: 8,
        duration: 301748122,
        category: "Data Science",
        students: 6995,
        level: 'l3',
        price: 65.11,
        rating: 4.33,
        earning: 105919,
        status: 'published'
    },
    {
        course_id: 24,
        name: "Big Data Analytics and Cloud Computing",
        image: "/images/800x600.png",
        lesson_count: 24,
        duration: 41698073,
        category: "Ruby on Rails",
        students: 64278,
        level: 'l1',
        price: 53.24,
        rating: 4.75,
        earning: 537036,
        status: 'published'
    },
    {
        course_id: 25,
        name: "Bioinformatics and Computational Biology",
        image: "/images/800x600.png",
        lesson_count: 24,
        duration: 308814716,
        category: "Data Analytics",
        students: 6174,
        level: 'l3',
        price: 54.57,
        rating: 4.9,
        earning: 303000,
        status: 'rejected'
    },
    {
        course_id: 26,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 6,
        duration: 46616665,
        category: "Software Testing",
        students: 5900,
        level: 'l2',
        price: 42.04,
        rating: 4.64,
        earning: 817258,
        status: 'draft'
    },
    {
        course_id: 27,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 21,
        duration: 3346297,
        category: "Data Visualization",
        students: 45612,
        level: 'l4',
        price: 75.38,
        rating: 4.03,
        earning: 797299,
        status: 'disabled'
    },
    {
        course_id: 28,
        name: "E-commerce and Web Applications",
        image: "/images/800x600.png",
        lesson_count: 45,
        duration: 52561357,
        category: "Software Architecture",
        students: 3959,
        level: 'l3',
        price: 18.68,
        rating: 4.15,
        earning: 42473,
        status: 'disabled'
    },
    {
        course_id: 29,
        name: "Data Visualization and Dashboard Design",
        image: "/images/800x600.png",
        lesson_count: 20,
        duration: 1785852,
        category: "Scrum",
        students: 72219,
        level: 'l2',
        price: 33.60,
        rating: 4.21,
        earning: 182136,
        status: 'draft'
    },
    {
        course_id: 30,
        name: "Software Testing and Quality Assurance",
        image: "/images/800x600.png",
        lesson_count: 46,
        duration: 344845480,
        category: "CSS",
        students: 44022,
        level: 'l2',
        price: 65.62,
        rating: 4.6,
        earning: 722325,
        status: 'rejected'
    },
    {
        course_id: 31,
        name: "Machine Learning and Data Science",
        image: "/images/800x600.png",
        lesson_count: 13,
        duration: 245665065,
        category: "Natural Language Processing",
        students: 40251,
        level: 'l3',
        price: 33.13,
        rating: 4.6,
        earning: 856186,
        status: 'published'
    },
    {
        course_id: 32,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 15,
        duration: 285974629,
        category: "Software Engineering",
        students: 72620,
        level: 'l4',
        price: 61.83,
        rating: 4.71,
        earning: 917119,
        status: 'disabled'
    },
    {
        course_id: 33,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 20,
        duration: 292108310,
        category: "Web Design",
        students: 22444,
        level: 'l2',
        price: 49.29,
        rating: 4.89,
        earning: 81431,
        status: 'draft'
    },
    {
        course_id: 34,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 17,
        duration: 356421596,
        category: "Data Mining",
        students: 87111,
        level: 'l4',
        price: 50.89,
        rating: 4.16,
        earning: 180901,
        status: 'published'
    },
    {
        course_id: 35,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 7,
        duration: 48292484,
        category: "DevOps",
        students: 20726,
        level: 'l3',
        price: 41.39,
        rating: 4.6,
        earning: 441886,
        status: 'published'
    },
    {
        course_id: 36,
        name: "Computational Creativity and Generative Art",
        image: "/images/800x600.png",
        lesson_count: 17,
        duration: 234682082,
        category: "Neural Networks",
        students: 94341,
        level: 'l3',
        price: 77.69,
        rating: 4.36,
        earning: 927619,
        status: 'rejected'
    },
    {
        course_id: 37,
        name: "Data Mi",
        image: "/images/800x600.png",
        lesson_count: 43,
        duration: 72108428,
        category: "Ruby on Rails",
        students: 47888,
        level: 'l2',
        price: 57.00,
        rating: 4.54,
        earning: 917716,
        status: 'rejected'
    },
    {
        course_id: 38,
        name: "Human-Computer Interaction and User Experience Design",
        image: "/images/800x600.png",
        lesson_count: 7,
        duration: 77847035,
        category: "Web Development",
        students: 62331,
        level: 'l4',
        price: 70.35,
        rating: 4.58,
        earning: 909896,
        status: 'rejected'
    },
    {
        course_id: 39,
        name: "Computer Graphics and Animation",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 188399890,
        category: "Software Development",
        students: 71302,
        level: 'l2',
        price: 89.87,
        rating: 4.48,
        earning: 177458,
        status: 'published'
    },
    {
        course_id: 40,
        name: "Artificial Intelligence and Expert Systems",
        image: "/images/800x600.png",
        lesson_count: 14,
        duration: 262964359,
        category: "Software Development",
        students: 52863,
        level: 'l1',
        price: 72.89,
        rating: 4.29,
        earning: 551495,
        status: 'disabled'
    },
    {
        course_id: 41,
        name: "Computer Ethics and Professional Responsibility",
        image: "/images/800x600.png",
        lesson_count: 47,
        duration: 48307445,
        category: "Data Visualization",
        students: 25917,
        level: 'l4',
        price: 32.39,
        rating: 4.86,
        earning: 590762,
        status: 'published'
    },
    {
        course_id: 42,
        name: "Big Data Analytics and Cloud Computing",
        image: "/images/800x600.png",
        lesson_count: 16,
        duration: 265280780,
        category: "Data Analytics",
        students: 67186,
        level: 'l1',
        price: 14.90,
        rating: 4.99,
        earning: 530875,
        status: 'published'
    },
    {
        course_id: 43,
        name: "Data Visualization and Dashboard Design",
        image: "/images/800x600.png",
        lesson_count: 29,
        duration: 105047238,
        category: "CSS",
        students: 57954,
        level: 'l4',
        price: 86.28,
        rating: 4.83,
        earning: 370880,
        status: 'in-review'
    },
    {
        course_id: 44,
        name: "Computer Vision and Image Processing",
        image: "/images/800x600.png",
        lesson_count: 32,
        duration: 246943579,
        category: "Data Visualization",
        students: 84463,
        level: 'l1',
        price: 58.91,
        rating: 4.46,
        earning: 767384,
        status: 'draft'
    },
    {
        course_id: 45,
        name: "Computer Ethics and Professional Responsibility",
        image: "/images/800x600.png",
        lesson_count: 18,
        duration: 300802734,
        category: "Natural Language Processing",
        students: 12626,
        level: 'l2',
        price: 66.71,
        rating: 4.93,
        earning: 633337,
        status: 'in-review'
    },
    {
        course_id: 46,
        name: "Computer Ethics and Professional Responsibility",
        image: "/images/800x600.png",
        lesson_count: 7,
        duration: 241992574,
        category: "PHP",
        students: 84210,
        level: 'l4',
        price: 45.57,
        rating: 4.58,
        earning: 248472,
        status: 'in-review'
    },
    {
        course_id: 47,
        name: "Digital Signal Processing and Audio Engineering",
        image: "/images/800x600.png",
        lesson_count: 14,
        duration: 101278189,
        category: "Data Analytics",
        students: 84335,
        level: 'l4',
        price: 68.81,
        rating: 4.45,
        earning: 311403,
        status: 'published'
    },
    {
        course_id: 48,
        name: "Data Visualization and Dashboard Design",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 202669185,
        category: "Data Visualization",
        students: 70651,
        level: 'l3',
        price: 51.39,
        rating: 4.78,
        earning: 986165,
        status: 'published'
    },
    {
        course_id: 49,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 27,
        duration: 67452507,
        category: "Data Analytics",
        students: 52493,
        level: 'l3',
        price: 77.11,
        rating: 4.68,
        earning: 741658,
        status: 'in-review'
    },
    {
        course_id: 50,
        name: "Computational Logic and Formal Methods",
        image: "/images/800x600.png",
        lesson_count: 9,
        duration: 174158278,
        category: "Data Mining",
        students: 31669,
        level: 'l2',
        price: 58.78,
        rating: 4.23,
        earning: 485977,
        status: 'in-review'
    },
    {
        course_id: 51,
        name: "Software Architecture and Design Patterns",
        image: "/images/800x600.png",
        lesson_count: 18,
        duration: 34742435,
        category: "Natural Language Processing",
        students: 77613,
        level: 'l4',
        price: 97.04,
        rating: 4.26,
        earning: 267293,
        status: 'draft'
    },
    {
        course_id: 52,
        name: "Software Architecture and Design Patterns",
        image: "/images/800x600.png",
        lesson_count: 32,
        duration: 33772809,
        category: "Software Development",
        students: 56594,
        level: 'l2',
        price: 69.05,
        rating: 4.78,
        earning: 659329,
        status: 'in-review'
    },
    {
        course_id: 53,
        name: "Virtual Reality and Augmented Reality",
        image: "/images/800x600.png",
        lesson_count: 31,
        duration: 307079983,
        category: "Artificial Intelligence",
        students: 18057,
        level: 'l2',
        price: 82.80,
        rating: 4.2,
        earning: 889231,
        status: 'draft'
    },
    {
        course_id: 54,
        name: "ning and Business Intelligence",
        image: "/images/800x600.png",
        lesson_count: 11,
        duration: 75439867,
        category: "Ruby on Rails",
        students: 63216,
        level: 'l1',
        price: 55.74,
        rating: 4.28,
        earning: 828239,
        status: 'published'
    },
    {
        course_id: 55,
        name: "Human-Computer Interaction and User Experience Design",
        image: "/images/800x600.png",
        lesson_count: 19,
        duration: 348169812,
        category: "Data Visualization",
        students: 14694,
        level: 'l2',
        price: 22.57,
        rating: 4.79,
        earning: 961792,
        status: 'published'
    },
    {
        course_id: 56,
        name: "Software Architecture and Design Patterns",
        image: "/images/800x600.png",
        lesson_count: 37,
        duration: 27136111,
        category: "Git",
        students: 46590,
        level: 'l3',
        price: 41.86,
        rating: 4.81,
        earning: 524670,
        status: 'published'
    },
    {
        course_id: 57,
        name: "Virtual Reality and Augmented Reality",
        image: "/images/800x600.png",
        lesson_count: 11,
        duration: 103874307,
        category: "Software Engineering",
        students: 9911,
        level: 'l2',
        price: 23.96,
        rating: 4.36,
        earning: 645977,
        status: 'draft'
    },
    {
        course_id: 58,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 32,
        duration: 350300288,
        category: "Scrum",
        students: 49613,
        level: 'l3',
        price: 91.18,
        rating: 4.22,
        earning: 580424,
        status: 'draft'
    },
    {
        course_id: 59,
        name: "Artificial Intelligence and Expert Systems",
        image: "/images/800x600.png",
        lesson_count: 18,
        duration: 172992494,
        category: "Agile Methodologies",
        students: 96564,
        level: 'l4',
        price: 97.81,
        rating: 4.96,
        earning: 468922,
        status: 'in-review'
    },
    {
        course_id: 60,
        name: "Natural Language Processing and Text Mining",
        image: "/images/800x600.png",
        lesson_count: 50,
        duration: 147699865,
        category: "Neural Networks",
        students: 22940,
        level: 'l1',
        price: 51.77,
        rating: 4.04,
        earning: 822532,
        status: 'published'
    },
    {
        course_id: 61,
        name: "Artificial Neural Networks and Deep Learning",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 336046182,
        category: "Web Development",
        students: 13564,
        level: 'l3',
        price: 46.48,
        rating: 4.94,
        earning: 679054,
        status: 'rejected'
    },
    {
        course_id: 62,
        name: "Computational Creativity and Generative Art",
        image: "/images/800x600.png",
        lesson_count: 39,
        duration: 143609241,
        category: "Natural Language Processing",
        students: 45627,
        level: 'l4',
        price: 27.83,
        rating: 4.67,
        earning: 624416,
        status: 'disabled'
    },
    {
        course_id: 63,
        name: "Information Retrieval and Web Search",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 289159888,
        category: "Data Mining",
        students: 35738,
        level: 'l2',
        price: 34.41,
        rating: 4.51,
        earning: 650772,
        status: 'rejected'
    },
    {
        course_id: 64,
        name: "Cryptography and Network Security",
        image: "/images/800x600.png",
        lesson_count: 50,
        duration: 127141160,
        category: "Software Testing",
        students: 10544,
        level: 'l3',
        price: 67.53,
        rating: 4.01,
        earning: 995772,
        status: 'draft'
    },
    {
        course_id: 65,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 5,
        duration: 298529887,
        category: "Data Analytics",
        students: 73310,
        level: 'l2',
        price: 80.64,
        rating: 4.08,
        earning: 838072,
        status: 'in-review'
    },
    {
        course_id: 66,
        name: "Information Retrieval and Web Search",
        image: "/images/800x600.png",
        lesson_count: 35,
        duration: 170598193,
        category: "Ruby on Rails",
        students: 92077,
        level: 'l3',
        price: 97.05,
        rating: 4.35,
        earning: 60055,
        status: 'draft'
    },
    {
        course_id: 67,
        name: "E-commerce and Web Applications",
        image: "/images/800x600.png",
        lesson_count: 36,
        duration: 34536516,
        category: "Web Development",
        students: 26124,
        level: 'l3',
        price: 29.14,
        rating: 4.63,
        earning: 140434,
        status: 'rejected'
    },
    {
        course_id: 68,
        name: "E-commerce and Web Applications",
        image: "/images/800x600.png",
        lesson_count: 47,
        duration: 173786632,
        category: "Software Engineering",
        students: 47899,
        level: 'l3',
        price: 33.63,
        rating: 4.62,
        earning: 406549,
        status: 'disabled'
    },
    {
        course_id: 69,
        name: "Artificial Intelligence and Expert Systems",
        image: "/images/800x600.png",
        lesson_count: 10,
        duration: 168598517,
        category: "PHP",
        students: 94158,
        level: 'l2',
        price: 51.13,
        rating: 4.11,
        earning: 5850,
        status: 'in-review'
    },
    {
        course_id: 70,
        name: "Big Data Analytics and Cloud Computing",
        image: "/images/800x600.png",
        lesson_count: 8,
        duration: 134029161,
        category: "Neural Networks",
        students: 5541,
        level: 'l3',
        price: 58.06,
        rating: 4.25,
        earning: 1029,
        status: 'in-review'
    },
    {
        course_id: 71,
        name: "Blockchain Technology and Smart Contracts",
        image: "/images/800x600.png",
        lesson_count: 31,
        duration: 255276285,
        category: "Computer Vision",
        students: 98247,
        level: 'l3',
        price: 24.14,
        rating: 4.87,
        earning: 658201,
        status: 'in-review'
    },
    {
        course_id: 72,
        name: "Human-Computer Interaction and User Experience Design",
        image: "/images/800x600.png",
        lesson_count: 14,
        duration: 323720640,
        category: "Natural Language Processing",
        students: 44887,
        level: 'l4',
        price: 91.87,
        rating: 4.52,
        earning: 276704,
        status: 'rejected'
    },
    {
        course_id: 73,
        name: "Computational Creativity and Generative Art",
        image: "/images/800x600.png",
        lesson_count: 50,
        duration: 269935209,
        category: "GitHub",
        students: 57568,
        level: 'l1',
        price: 97.86,
        rating: 4.73,
        earning: 327501,
        status: 'rejected'
    },
    {
        course_id: 74,
        name: "Machine Learning and Data Science",
        image: "/images/800x600.png",
        lesson_count: 32,
        duration: 98723526,
        category: "Web Development",
        students: 10738,
        level: 'l1',
        price: 43.73,
        rating: 4.89,
        earning: 650175,
        status: 'disabled'
    },
    {
        course_id: 75,
        name: "Bioinformatics and Computational Biology",
        image: "/images/800x600.png",
        lesson_count: 47,
        duration: 344454738,
        category: "Scrum",
        students: 74321,
        level: 'l4',
        price: 29.87,
        rating: 4.59,
        earning: 879217,
        status: 'disabled'
    },
    {
        course_id: 76,
        name: "Human-Computer Interaction and User Experience Design",
        image: "/images/800x600.png",
        lesson_count: 10,
        duration: 208730622,
        category: "Neural Networks",
        students: 53327,
        level: 'l4',
        price: 31.31,
        rating: 4.4,
        earning: 279094,
        status: 'published'
    },
    {
        course_id: 77,
        name: "Machine Learning and Data Science",
        image: "/images/800x600.png",
        lesson_count: 29,
        duration: 326014774,
        category: "Data Visualization",
        students: 94061,
        level: 'l3',
        price: 86.22,
        rating: 4.43,
        earning: 875796,
        status: 'in-review'
    },
    {
        course_id: 78,
        name: "Cryptography and Network Security",
        image: "/images/800x600.png",
        lesson_count: 22,
        duration: 302513675,
        category: "Natural Language Processing",
        students: 39944,
        level: 'l3',
        price: 49.38,
        rating: 4.27,
        earning: 883281,
        status: 'rejected'
    },
    {
        course_id: 79,
        name: "Programming Languages and Compilers",
        image: "/images/800x600.png",
        lesson_count: 8,
        duration: 90063003,
        category: "JavaScript",
        students: 10140,
        level: 'l2',
        price: 60.86,
        rating: 4.79,
        earning: 748225,
        status: 'rejected'
    },
    {
        course_id: 80,
        name: "Virtual Reality and Augmented Reality",
        image: "/images/800x600.png",
        lesson_count: 17,
        duration: 36795210,
        category: "PHP",
        students: 82351,
        level: 'l1',
        price: 15.93,
        rating: 4.74,
        earning: 192196,
        status: 'in-review'
    },
    {
        course_id: 81,
        name: "Software Architecture and Design Patterns",
        image: "/images/800x600.png",
        lesson_count: 12,
        duration: 170278686,
        category: "Web Design",
        students: 67902,
        level: 'l1',
        price: 66.41,
        rating: 4.36,
        earning: 310538,
        status: 'disabled'
    },
    {
        course_id: 82,
        name: "Digital Signal Processing and Audio Engineering",
        image: "/images/800x600.png",
        lesson_count: 11,
        duration: 348977472,
        category: "Data Science",
        students: 12008,
        level: 'l1',
        price: 97.42,
        rating: 4.29,
        earning: 3451,
        status: 'draft'
    },
    {
        course_id: 83,
        name: "Embedded Systems and Robotics",
        image: "/images/800x600.png",
        lesson_count: 37,
        duration: 324589898,
        category: "GitHub",
        students: 31310,
        level: 'l3',
        price: 80.64,
        rating: 4.89,
        earning: 117865,
        status: 'draft'
    },
    {
        course_id: 84,
        name: "Artificial Neural Networks and Deep Learning",
        image: "/images/800x600.png",
        lesson_count: 7,
        duration: 43885787,
        category: "Data Analytics",
        students: 71547,
        level: 'l1',
        price: 27.58,
        rating: 4.87,
        earning: 850708,
        status: 'in-review'
    },
    {
        course_id: 85,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 8,
        duration: 240816652,
        category: "Data Mining",
        students: 70078,
        level: 'l2',
        price: 18.33,
        rating: 4.27,
        earning: 608414,
        status: 'draft'
    },
    {
        course_id: 86,
        name: "Wireless Networks and Mobile Computing",
        image: "/images/800x600.png",
        lesson_count: 19,
        duration: 99446297,
        category: "Artificial Intelligence",
        students: 34100,
        level: 'l3',
        price: 31.79,
        rating: 4.2,
        earning: 886562,
        status: 'disabled'
    },
    {
        course_id: 87,
        name: "Programming Languages and Compilers",
        image: "/images/800x600.png",
        lesson_count: 24,
        duration: 102555128,
        category: "DevOps",
        students: 77228,
        level: 'l1',
        price: 98.53,
        rating: 4.96,
        earning: 363861,
        status: 'in-review'
    },
    {
        course_id: 88,
        name: "Computer Ethics and Professional Responsibility",
        image: "/images/800x600.png",
        lesson_count: 33,
        duration: 340974403,
        category: "WordPress",
        students: 75545,
        level: 'l3',
        price: 82.77,
        rating: 4.43,
        earning: 778085,
        status: 'published'
    },
    {
        course_id: 89,
        name: "Programming Languages and Compilers",
        image: "/images/800x600.png",
        lesson_count: 37,
        duration: 164441172,
        category: "Software Testing",
        students: 80111,
        level: 'l3',
        price: 21.73,
        rating: 4.86,
        earning: 549142,
        status: 'published'
    },
    {
        course_id: 90,
        name: "Big Data Analytics and Cloud Computing",
        image: "/images/800x600.png",
        lesson_count: 19,
        duration: 291899547,
        category: "JavaScript",
        students: 33861,
        level: 'l2',
        price: 47.03,
        rating: 4.07,
        earning: 436091,
        status: 'draft'
    },
    {
        course_id: 91,
        name: "Quantum Computing and Information Theory",
        image: "/images/800x600.png",
        lesson_count: 45,
        duration: 180696502,
        category: "Natural Language Processing",
        students: 86848,
        level: 'l1',
        price: 74.68,
        rating: 4.63,
        earning: 667368,
        status: 'in-review'
    },
    {
        course_id: 92,
        name: "Computer Graphics and Animation",
        image: "/images/800x600.png",
        lesson_count: 44,
        duration: 233178590,
        category: "Artificial Intelligence",
        students: 11014,
        level: 'l1',
        price: 16.94,
        rating: 4.58,
        earning: 104899,
        status: 'rejected'
    },
    {
        course_id: 93,
        name: "Social Media and Network Analysis",
        image: "/images/800x600.png",
        lesson_count: 30,
        duration: 284663192,
        category: "Neural Networks",
        students: 55829,
        level: 'l1',
        price: 81.17,
        rating: 4.32,
        earning: 201605,
        status: 'published'
    },
    {
        course_id: 94,
        name: "Software Testing and Quality Assurance",
        image: "/images/800x600.png",
        lesson_count: 39,
        duration: 29900835,
        category: "Ruby on Rails",
        students: 54578,
        level: 'l2',
        price: 40.29,
        rating: 4.71,
        earning: 7326,
        status: 'in-review'
    },
    {
        course_id: 95,
        name: "Natural Language Processing and Text Mining",
        image: "/images/800x600.png",
        lesson_count: 28,
        duration: 38690343,
        category: "Data Science",
        students: 81104,
        level: 'l3',
        price: 62.94,
        rating: 4.43,
        earning: 188428,
        status: 'draft'
    },
    {
        course_id: 96,
        name: "Computational Creativity and Generative Art",
        image: "/images/800x600.png",
        lesson_count: 29,
        duration: 254797473,
        category: "Web Development",
        students: 7292,
        level: 'l2',
        price: 71.52,
        rating: 4.6,
        earning: 121741,
        status: 'draft'
    },
    {
        course_id: 97,
        name: "Game Design and Development",
        image: "/images/800x600.png",
        lesson_count: 39,
        duration: 160509825,
        category: "Data Science",
        students: 15021,
        level: 'l2',
        price: 50.61,
        rating: 4.37,
        earning: 153358,
        status: 'in-review'
    },
    {
        course_id: 98,
        name: "Machine Learning and Data Science",
        image: "/images/800x600.png",
        lesson_count: 38,
        duration: 279210303,
        category: "Web Design",
        students: 77294,
        level: 'l1',
        price: 95.46,
        rating: 4.77,
        earning: 220871,
        status: 'in-review'
    },
    {
        course_id: 99,
        name: "Software Architecture and Design Patterns",
        image: "/images/800x600.png",
        lesson_count: 7,
        duration: 288388139,
        category: "Web Development",
        students: 44465,
        level: 'l3',
        price: 85.21,
        rating: 4.17,
        earning: 255715,
        status: 'rejected'
    },
    {
        course_id: 100,
        name: "Artificial Neural Networks and Deep Learning",
        image: "/images/800x600.png",
        lesson_count: 14,
        duration: 246060381,
        category: "Neural Networks",
        students: 7125,
        level: 'l2',
        price: 50.29,
        rating: 4.83,
        earning: 965306,
        status: 'disabled'
    },
];
