export const mediaList = [
    {
        media_id: 1,
        name: "Big Data Analytics and Cloud Computing",
        file_name: "PosuereMetus.mp3",
        file_size: 45256734585,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 70,
    },
    {
        media_id: 2,
        name: "Cryptography and Network Security",
        file_name: "Tempus.mp4",
        file_size: 60844538135,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 24,
    },
    {
        media_id: 3,
        name: "Blockchain Technology and Smart Contracts",
        file_name: "AmetConsectetuer.mp3",
        file_size: 75874879866,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 89,
    },
    {
        media_id: 4,
        name: "Computational Creativity and Generative Art",
        file_name: "CondimentumIdLuctus.pdf",
        file_size: 17305650712,
        permission: { key: "view", title: "Only View" },
        assign_count: 11,
    },
    {
        media_id: 5,
        name: "Computer Vision and Image Processing",
        file_name: "Dictumst.pdf",
        file_size: 97392154216,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 79,
    },
    {
        media_id: 6,
        name: "Computational Creativity and Generative Art",
        file_name: "SitAmet.mp3",
        file_size: 22854579862,
        permission: { key: "view", title: "Only View" },
        assign_count: 96,
    },
    {
        media_id: 7,
        name: "Artificial Intelligence and Expert Systems",
        file_name: "PotentiInEleifend.mp4",
        file_size: 35799023508,
        permission: { key: "view", title: "Only View" },
        assign_count: 48,
    },
    {
        media_id: 8,
        name: "Bioinformatics and Computational Biology",
        file_name: "SollicitudinMiSit.mp4",
        file_size: 90431405988,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 47,
    },
    {
        media_id: 9,
        name: "Software Testing and Quality Assurance",
        file_name: "VelNulla.mp3",
        file_size: 1738675448,
        permission: { key: "view", title: "Only View" },
        assign_count: 49,
    },
    {
        media_id: 10,
        name: "Programming Languages and Compilers",
        file_name: "At.mp3",
        file_size: 90584207100,
        permission: { key: "view", title: "Only View" },
        assign_count: 72,
    },
    {
        media_id: 11,
        name: "Operating Systems and System Programming",
        file_name: "NullaEgetEros.pdf",
        file_size: 68577393931,
        permission: { key: "view", title: "Only View" },
        assign_count: 32,
    },
    {
        media_id: 12,
        name: "Computational Creativity and Generative Art",
        file_name: "QuisTurpisSed.ppt",
        file_size: 92371122794,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 21,
    },
    {
        media_id: 13,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "NonPretium.mp3",
        file_size: 28126686624,
        permission: { key: "view", title: "Only View" },
        assign_count: 64,
    },
    {
        media_id: 14,
        name: "Operating Systems and System Programming",
        file_name: "Elit.mp3",
        file_size: 23988602675,
        permission: { key: "view", title: "Only View" },
        assign_count: 53,
    },
    {
        media_id: 15,
        name: "Cryptography and Network Security",
        file_name: "In.mp4",
        file_size: 78082791222,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 27,
    },
    {
        media_id: 16,
        name: "Artificial Intelligence and Expert Systems",
        file_name: "CubiliaCurae.pdf",
        file_size: 38504210871,
        permission: { key: "view", title: "Only View" },
        assign_count: 48,
    },
    {
        media_id: 17,
        name: "Machine Learning and Data Science",
        file_name: "LectusIn.mp4",
        file_size: 38037525589,
        permission: { key: "view", title: "Only View" },
        assign_count: 55,
    },
    {
        media_id: 18,
        name: "Information Retrieval and Web Search",
        file_name: "Congue.mp4",
        file_size: 18691670095,
        permission: { key: "view", title: "Only View" },
        assign_count: 99,
    },
    {
        media_id: 19,
        name: "Programming Languages and Compilers",
        file_name: "ArcuAdipiscingMolestie.ppt",
        file_size: 11041129023,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 60,
    },
    {
        media_id: 20,
        name: "Programming Languages and Compilers",
        file_name: "SitAmetDiam.ppt",
        file_size: 30037344166,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 23,
    },
    {
        media_id: 21,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "Ut.pdf",
        file_size: 31248434500,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 33,
    },
    {
        media_id: 22,
        name: "Information Retrieval and Web Search",
        file_name: "Ac.ppt",
        file_size: 2993620954,
        permission: { key: "view", title: "Only View" },
        assign_count: 58,
    },
    {
        media_id: 23,
        name: "Digital Signal Processing and Audio Engineering",
        file_name: "EtiamVelAugue.ppt",
        file_size: 79449175102,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 96,
    },
    {
        media_id: 24,
        name: "Wireless Networks and Mobile Computing",
        file_name: "FusceConsequatNulla.mp4",
        file_size: 24174531989,
        permission: { key: "view", title: "Only View" },
        assign_count: 86,
    },
    {
        media_id: 25,
        name: "Quantum Computing and Information Theory",
        file_name: "Ut.pdf",
        file_size: 73029196412,
        permission: { key: "view", title: "Only View" },
        assign_count: 68,
    },
    {
        media_id: 26,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "TempusVivamusIn.mp3",
        file_size: 93697343018,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 52,
    },
    {
        media_id: 27,
        name: "Operating Systems and System Programming",
        file_name: "LuctusEtUltrices.mp4",
        file_size: 19514436775,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 24,
    },
    {
        media_id: 28,
        name: "Wireless Networks and Mobile Computing",
        file_name: "SapienCursus.mp4",
        file_size: 14029474658,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 46,
    },
    {
        media_id: 29,
        name: "E-commerce and Web Applications",
        file_name: "CuraeDonecPharetra.mp4",
        file_size: 63305936079,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 79,
    },
    {
        media_id: 30,
        name: "Data Mi",
        file_name: "Erat.mp4",
        file_size: 72758455160,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 44,
    },
    {
        media_id: 31,
        name: "Virtual Reality and Augmented Reality",
        file_name: "PulvinarSed.ppt",
        file_size: 83384394160,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 51,
    },
    {
        media_id: 32,
        name: "Big Data Analytics and Cloud Computing",
        file_name: "JustoMorbi.mp3",
        file_size: 54182208933,
        permission: { key: "view", title: "Only View" },
        assign_count: 47,
    },
    {
        media_id: 33,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "FermentumDonecUt.mp4",
        file_size: 75447452691,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 49,
    },
    {
        media_id: 34,
        name: "Natural Language Processing and Text Mining",
        file_name: "DuiLuctus.ppt",
        file_size: 31155563757,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 74,
    },
    {
        media_id: 35,
        name: "Software Testing and Quality Assurance",
        file_name: "Venenatis.mp4",
        file_size: 57266319328,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 82,
    },
    {
        media_id: 36,
        name: "Computational Logic and Formal Methods",
        file_name: "ScelerisqueMauris.mp3",
        file_size: 61198039562,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 70,
    },
    {
        media_id: 37,
        name: "Information Retrieval and Web Search",
        file_name: "Nisl.mp3",
        file_size: 17196772127,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 66,
    },
    {
        media_id: 38,
        name: "Wireless Networks and Mobile Computing",
        file_name: "AliquamLacusMorbi.mp3",
        file_size: 6178867077,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 62,
    },
    {
        media_id: 39,
        name: "Machine Learning and Data Science",
        file_name: "PlateaDictumstEtiam.mp4",
        file_size: 84697157700,
        permission: { key: "view", title: "Only View" },
        assign_count: 66,
    },
    {
        media_id: 40,
        name: "Computer Vision and Image Processing",
        file_name: "Faucibus.ppt",
        file_size: 93426133505,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 88,
    },
    {
        media_id: 41,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "Phasellus.mp4",
        file_size: 12803293900,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 33,
    },
    {
        media_id: 42,
        name: "Blockchain Technology and Smart Contracts",
        file_name: "LacusCurabiturAt.mp3",
        file_size: 2120407067,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 86,
    },
    {
        media_id: 43,
        name: "Virtual Reality and Augmented Reality",
        file_name: "HacHabitassePlatea.mp4",
        file_size: 48147172733,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 23,
    },
    {
        media_id: 44,
        name: "Cryptography and Network Security",
        file_name: "Volutpat.mp3",
        file_size: 37949093470,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 12,
    },
    {
        media_id: 45,
        name: "Software Architecture and Design Patterns",
        file_name: "Odio.mp4",
        file_size: 50962110332,
        permission: { key: "view", title: "Only View" },
        assign_count: 54,
    },
    {
        media_id: 46,
        name: "Computer Vision and Image Processing",
        file_name: "PraesentIdMassa.mp3",
        file_size: 59517265041,
        permission: { key: "view", title: "Only View" },
        assign_count: 58,
    },
    {
        media_id: 47,
        name: "Wireless Networks and Mobile Computing",
        file_name: "Erat.mp4",
        file_size: 88238936950,
        permission: { key: "view", title: "Only View" },
        assign_count: 75,
    },
    {
        media_id: 48,
        name: "Computer Graphics and Animation",
        file_name: "NuncCommodo.mp3",
        file_size: 47391544593,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 27,
    },
    {
        media_id: 49,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "TinciduntEu.pdf",
        file_size: 76528601765,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 34,
    },
    {
        media_id: 50,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "EgetOrci.mp4",
        file_size: 47853374894,
        permission: { key: "view", title: "Only View" },
        assign_count: 42,
    },
    {
        media_id: 51,
        name: "Computer Graphics and Animation",
        file_name: "Magna.mp4",
        file_size: 60038594899,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 95,
    },
    {
        media_id: 52,
        name: "Virtual Reality and Augmented Reality",
        file_name: "Integer.mp3",
        file_size: 8268999471,
        permission: { key: "view", title: "Only View" },
        assign_count: 89,
    },
    {
        media_id: 53,
        name: "Bioinformatics and Computational Biology",
        file_name: "Mauris.mp3",
        file_size: 5861685918,
        permission: { key: "view", title: "Only View" },
        assign_count: 88,
    },
    {
        media_id: 54,
        name: "Blockchain Technology and Smart Contracts",
        file_name: "APede.mp4",
        file_size: 43867331454,
        permission: { key: "view", title: "Only View" },
        assign_count: 76,
    },
    {
        media_id: 55,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "Nec.mp3",
        file_size: 68209506052,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 94,
    },
    {
        media_id: 56,
        name: "Cryptography and Network Security",
        file_name: "CommodoPlacerat.mp3",
        file_size: 50824967957,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 87,
    },
    {
        media_id: 57,
        name: "Artificial Neural Networks and Deep Learning",
        file_name: "Cras.mp3",
        file_size: 31286835266,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 57,
    },
    {
        media_id: 58,
        name: "Information Retrieval and Web Search",
        file_name: "IntegerAcLeo.pdf",
        file_size: 41739132839,
        permission: { key: "view", title: "Only View" },
        assign_count: 79,
    },
    {
        media_id: 59,
        name: "Data Visualization and Dashboard Design",
        file_name: "SuscipitLigula.mp3",
        file_size: 45620817424,
        permission: { key: "view", title: "Only View" },
        assign_count: 96,
    },
    {
        media_id: 60,
        name: "Wireless Networks and Mobile Computing",
        file_name: "VestibulumSed.mp3",
        file_size: 29546458853,
        permission: { key: "view", title: "Only View" },
        assign_count: 15,
    },
    {
        media_id: 61,
        name: "Computer Vision and Image Processing",
        file_name: "EratTortorSollicitudin.mp4",
        file_size: 86990953068,
        permission: { key: "view", title: "Only View" },
        assign_count: 16,
    },
    {
        media_id: 62,
        name: "E-commerce and Web Applications",
        file_name: "NullaNislNunc.mp3",
        file_size: 44405172038,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 52,
    },
    {
        media_id: 63,
        name: "Artificial Neural Networks and Deep Learning",
        file_name: "LeoOdioPorttitor.mp4",
        file_size: 12526502086,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 25,
    },
    {
        media_id: 64,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "QuisLiberoNullam.pdf",
        file_size: 64624124641,
        permission: { key: "view", title: "Only View" },
        assign_count: 17,
    },
    {
        media_id: 65,
        name: "Computational Logic and Formal Methods",
        file_name: "InLiberoUt.mp3",
        file_size: 7707775307,
        permission: { key: "view", title: "Only View" },
        assign_count: 16,
    },
    {
        media_id: 66,
        name: "Artificial Intelligence and Expert Systems",
        file_name: "EtUltricesPosuere.pdf",
        file_size: 47796736317,
        permission: { key: "view", title: "Only View" },
        assign_count: 34,
    },
    {
        media_id: 67,
        name: "Digital Signal Processing and Audio Engineering",
        file_name: "Et.ppt",
        file_size: 97096825550,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 34,
    },
    {
        media_id: 68,
        name: "Artificial Intelligence and Expert Systems",
        file_name: "NamTristiqueTortor.mp4",
        file_size: 46556170337,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 30,
    },
    {
        media_id: 69,
        name: "Natural Language Processing and Text Mining",
        file_name: "DuisAtVelit.mp4",
        file_size: 63783444364,
        permission: { key: "view", title: "Only View" },
        assign_count: 58,
    },
    {
        media_id: 70,
        name: "Computational Logic and Formal Methods",
        file_name: "MaecenasLeo.mp4",
        file_size: 61484056819,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 78,
    },
    {
        media_id: 71,
        name: "Operating Systems and System Programming",
        file_name: "Eros.pdf",
        file_size: 86373824504,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 25,
    },
    {
        media_id: 72,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "FelisSedInterdum.mp3",
        file_size: 87571988877,
        permission: { key: "view", title: "Only View" },
        assign_count: 30,
    },
    {
        media_id: 73,
        name: "Programming Languages and Compilers",
        file_name: "Porttitor.mp3",
        file_size: 60890389820,
        permission: { key: "view", title: "Only View" },
        assign_count: 12,
    },
    {
        media_id: 74,
        name: "Social Media and Network Analysis",
        file_name: "EtiamFaucibusCursus.mp3",
        file_size: 56696640494,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 31,
    },
    {
        media_id: 75,
        name: "Virtual Reality and Augmented Reality",
        file_name: "DuiNecNisi.mp3",
        file_size: 71428810674,
        permission: { key: "view", title: "Only View" },
        assign_count: 72,
    },
    {
        media_id: 76,
        name: "Big Data Analytics and Cloud Computing",
        file_name: "PedeUllamcorperAugue.mp3",
        file_size: 7544662378,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 96,
    },
    {
        media_id: 77,
        name: "Social Media and Network Analysis",
        file_name: "IntegerAcLeo.mp3",
        file_size: 9384608832,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 71,
    },
    {
        media_id: 78,
        name: "Wireless Networks and Mobile Computing",
        file_name: "AtVelitVivamus.pdf",
        file_size: 76579574299,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 16,
    },
    {
        media_id: 79,
        name: "Machine Learning and Data Science",
        file_name: "ElementumPellentesqueQuisque.ppt",
        file_size: 25512215541,
        permission: { key: "view", title: "Only View" },
        assign_count: 39,
    },
    {
        media_id: 80,
        name: "Virtual Reality and Augmented Reality",
        file_name: "Id.mp4",
        file_size: 6084540320,
        permission: { key: "view", title: "Only View" },
        assign_count: 46,
    },
    {
        media_id: 81,
        name: "Embedded Systems and Robotics",
        file_name: "Eget.mp3",
        file_size: 25610373477,
        permission: { key: "view", title: "Only View" },
        assign_count: 48,
    },
    {
        media_id: 82,
        name: "Embedded Systems and Robotics",
        file_name: "Lorem.ppt",
        file_size: 36067402354,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 87,
    },
    {
        media_id: 83,
        name: "Programming Languages and Compilers",
        file_name: "LoremIpsum.pdf",
        file_size: 53696333764,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 56,
    },
    {
        media_id: 84,
        name: "Computational Creativity and Generative Art",
        file_name: "MagnaVulputateLuctus.ppt",
        file_size: 83402303403,
        permission: { key: "view", title: "Only View" },
        assign_count: 44,
    },
    {
        media_id: 85,
        name: "Virtual Reality and Augmented Reality",
        file_name: "VelNisl.mp3",
        file_size: 17141312541,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 34,
    },
    {
        media_id: 86,
        name: "Cryptography and Network Security",
        file_name: "Integer.mp4",
        file_size: 23065020815,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 15,
    },
    {
        media_id: 87,
        name: "Human-Computer Interaction and User Experience Design",
        file_name: "LaoreetUtRhoncus.pdf",
        file_size: 37821962340,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 50,
    },
    {
        media_id: 88,
        name: "Computational Logic and Formal Methods",
        file_name: "FusceConsequatNulla.ppt",
        file_size: 13659269216,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 64,
    },
    {
        media_id: 89,
        name: "Distributed Systems and Parallel Computing",
        file_name: "Aenean.mp4",
        file_size: 93255216641,
        permission: { key: "view", title: "Only View" },
        assign_count: 74,
    },
    {
        media_id: 90,
        name: "Bioinformatics and Computational Biology",
        file_name: "Grmp4daSem.mp4",
        file_size: 26614513814,
        permission: { key: "view", title: "Only View" },
        assign_count: 100,
    },
    {
        media_id: 91,
        name: "Computer Ethics and Professional Responsibility",
        file_name: "CongueVivamusMetus.pdf",
        file_size: 27189776817,
        permission: { key: "view", title: "Only View" },
        assign_count: 67,
    },
    {
        media_id: 92,
        name: "Information Retrieval and Web Search",
        file_name: "PedeLiberoQuis.mp4",
        file_size: 40574285832,
        permission: { key: "view", title: "Only View" },
        assign_count: 87,
    },
    {
        media_id: 93,
        name: "Data Mi",
        file_name: "MetusSapien.mp3",
        file_size: 6976506230,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 67,
    },
    {
        media_id: 94,
        name: "Wireless Networks and Mobile Computing",
        file_name: "Nulla.pdf",
        file_size: 80427826418,
        permission: { key: "view", title: "Only View" },
        assign_count: 57,
    },
    {
        media_id: 95,
        name: "Digital Signal Processing and Audio Engineering",
        file_name: "RutrumAc.ppt",
        file_size: 62156344502,
        permission: { key: "view", title: "Only View" },
        assign_count: 74,
    },
    {
        media_id: 96,
        name: "Operating Systems and System Programming",
        file_name: "LaciniaEratVestibulum.ppt",
        file_size: 12266966237,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 50,
    },
    {
        media_id: 97,
        name: "Big Data Analytics and Cloud Computing",
        file_name: "Grmp4da.mp3",
        file_size: 85147664708,
        permission: { key: "view", title: "Only View" },
        assign_count: 27,
    },
    {
        media_id: 98,
        name: "Software Testing and Quality Assurance",
        file_name: "VelitDonec.mp4",
        file_size: 29163285035,
        permission: { key: "can-edit", title: "Can Edit" },
        assign_count: 40,
    },
    {
        media_id: 99,
        name: "Quantum Computing and Information Theory",
        file_name: "NuncNislDuis.mp3",
        file_size: 94982352923,
        permission: { key: "view", title: "Only View" },
        assign_count: 54,
    },
    {
        media_id: 100,
        name: "Natural Language Processing and Text Mining",
        file_name: "UtMassaVolutpat.ppt",
        file_size: 71685142388,
        permission: { key: "view", title: "Only View" },
        assign_count: 96,
    },
];
